# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files, collect_dynamic_libs

# Collect Piper TTS data (espeak-ng-data is critical for phonemization)
piper_datas = collect_data_files('piper')
piper_binaries = collect_dynamic_libs('piper')

a = Analysis(
    ['focus_blocker_qt.py'],
    pathex=[],
    binaries=piper_binaries,
    datas=piper_datas + [
        # Core Python modules
        ('productivity_ai.py', '.'),
        ('gamification.py', '.'),
        ('game_state.py', '.'),
        ('core_logic.py', '.'),
        ('browser_monitor.py', '.'),
        ('lottery_animation.py', '.'),
        ('lottery_sounds.py', '.'),
        ('startup_sounds.py', '.'),
        ('bypass_logger.py', '.'),
        ('weight_control_tips.py', '.'),
        ('app_utils.py', '.'),
        # Dialog modules
        ('item_drop_dialog.py', '.'),
        ('level_up_dialog.py', '.'),
        ('styled_dialog.py', '.'),
        ('merge_dialog.py', '.'),
        ('session_complete_dialog.py', '.'),
        ('entity_drop_dialog.py', '.'),
        ('entity_encounter_dialog.py', '.'),
        ('emergency_cleanup_dialog.py', '.'),
        # Tab modules
        ('eye_protection_tab.py', '.'),
        ('entitidex_tab.py', '.'),
        ('city_tab.py', '.'),
        ('city_sounds.py', '.'),
        ('eye_protection_tips.py', '.'),
        ('productivity_tips.py', '.'),
        # Entitidex package
        ('entitidex', 'entitidex'),
        # City package
        ('city', 'city'),
        # Icons and assets
        ('icons', 'icons'),
        # Voice models for Piper TTS (optional, offline speech synthesis)
        ('voices', 'voices'),
    ],
    hiddenimports=[
        'productivity_ai', 
        'numpy',
        'gamification',
        'game_state',
        'core_logic',
        'browser_monitor',
        'lottery_animation',
        'lottery_sounds',
        'startup_sounds',
        'bypass_logger',
        'weight_control_tips',
        'app_utils',
        'item_drop_dialog',
        'level_up_dialog',
        'styled_dialog',
        'merge_dialog',
        'session_complete_dialog',
        'entity_drop_dialog',
        'entity_encounter_dialog',
        'emergency_cleanup_dialog',
        'eye_protection_tab',
        'entitidex_tab',
        'city_tab',
        'city_sounds',
        'eye_protection_tips',
        'productivity_tips',
        'entitidex',
        'city',
        'city.city_manager',
        'entitidex.celebration_audio',
        'entitidex.encounter_system',
        'entitidex.entitidex_manager',
        'entitidex.entity',
        'entitidex.entity_perks',
        'entitidex.entity_pools',
        'entitidex.catch_mechanics',
        'entitidex.progress_tracker',
        'entitidex.theme_completion',
        # PySide6 multimedia for audio synthesis
        'PySide6.QtMultimedia',
        # Piper TTS dependencies (optional - gracefully degrades if not available)
        'piper',
        'piper.voice',
        'onnxruntime',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['torch', 'transformers', 'sentence_transformers', 'huggingface_hub', 'tokenizers', 'torchaudio', 'torchvision', 'cupy', 'triton'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='PersonalLiberty',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['icons\\app.ico'],
    version='version_info.txt',
)
